# Generated by Django 4.2.15 on 2024-10-13 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("abdm", "0015_abhanumber_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abhanumber",
            name="txn_id",
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("reference_id", models.CharField(max_length=100)),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Create Or Link Abha Number"),
                            (2, "Create Abha Address"),
                            (3, "Scan And Share"),
                            (4, "Link Care Context"),
                            (5, "Exchange Data"),
                            (6, "Access Data"),
                        ]
                    ),
                ),
                ("meta_data", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
