# Generated by Django 5.1.3 on 2025-01-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0015_remove_abhanumber_txn_id_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abhanumber',
            old_name='patient',
            new_name='deprecated_patient',
        ),
    ]
