# Generated by Django 5.1.3 on 2025-01-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0016_rename_patient_abhanumber_deprecated_patient'),
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abhanumber',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abha_number', to='emr.patient'),
        ),
    ]
