# Generated by Django 5.1.4 on 2025-01-20 05:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0017_abhanumber_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentartefact',
            name='hi_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Prescription', 'Prescription'), ('DiagnosticReport', 'Diagnostic Report'), ('OPConsultation', 'Op Consultation'), ('DischargeSummary', 'Discharge Summary'), ('ImmunizationRecord', 'Immunization Record'), ('HealthDocumentRecord', 'Record Artifact'), ('WellnessRecord', 'Wellness Record'), ('Invoice', 'Invoice')], max_length=20), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='consentrequest',
            name='hi_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Prescription', 'Prescription'), ('DiagnosticReport', 'Diagnostic Report'), ('OPConsultation', 'Op Consultation'), ('DischargeSummary', 'Discharge Summary'), ('ImmunizationRecord', 'Immunization Record'), ('HealthDocumentRecord', 'Record Artifact'), ('WellnessRecord', 'Wellness Record'), ('Invoice', 'Invoice')], max_length=20), default=list, size=None),
        ),
    ]
